name = "animekai-backend"
main = "worker.js"
compatibility_date = "2024-03-01"

[vars]
JWT_SECRET = "super-secure-high-entropy-jwt-secret-key-change-this"

[[d1_databases]]
binding = "DB"
database_name = "alnuraraf_sql_d1"
database_id = "be7e97d9-b7ee-449c-9de5-7468fd570d92"

[assets]
directory = "./public"
binding = "ASSETS"
